export default {
  SET_USER: "SET_USER",
  SET_LOADING: "SET_LOADING",
  SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",
  SET_LOGOUT: "SET_LOGOUT",
  //BOOKS
  SET_BOOK: "SET_BOOK",
  SET_CHAPTERS: "SET_CHAPTERS",
};
