// Generated by https://quicktype.io

import { UserT } from './user';

export interface Book {
  bookId?: string;
  bookContent?: Chapter[];
  bookCategories?: BookCategory[];
  bookDate?: string;
  bookSize?: string;
  bookAge?: string;
  authorId: UserT;
  cover?: string;
  bookTitle?: string;
  bookRating: number;
  updatedAt?: string;
  createdAt?: string;
  saveInDraft?: boolean;
}

export interface BookCategory {
  categoryId: string;
  nameCategory: string;
  subCategory: string;
  cover: string;
  description: string;
  population: number;
}

export interface Chapter {
  chapterId: number;
  chapterTitle: string;
  chapterContent: string | [];
}
