// Generated by https://quicktype.io

import { UserT } from "./user";

export interface Thoughts {
    thoughtId?:       string;
    thoughtTitle:    string;
    thoughtContent:  string;
    thoughtComments?: string;
    thoughtViews:    number;
    thoughtShare?:    string;
    authorId:        UserT | string;
    thoughtBadge?:    string;
    belongsToBook?:   string;
    status?:          string;
    createdAt?:       string;
    updatedAt?:       string;
}
